#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define FUNCONF_USE_DEBUGPRINTF 0
#define FUNCONF_USE_UARTPRINTF  1
#define FUNCONF_UART_PRINTF_BAUD 115200
#define FUNCONF_DEBUG_HARDFAULT 1
// #define FUNCONF_SYSTEM_CORE_CLOCK 144000000

#define FUNCONF_USE_HSI             0
#define FUNCONF_USE_HSE             1

#endif

