#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define FUNCONF_USE_DEBUGPRINTF 1
#define FUNCONF_DEBUG_HARDFAULT 1
#define FUNCONF_SYSTEM_CORE_CLOCK 144000000

// Takes up 400B
#define FUNCONF_OVERRIDE_STARTUP 0

#endif

